package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/tamnd/bento/pkg/build"
)

// newBuildCmd is the entry point for the ahead-of-time build path: type-checking
// an entry module, lowering it to Go, and compiling that Go to a single native
// binary. The lowering covers a growing subset of the language; a construct
// outside it fails the build with the compiler's own message rather than
// emitting a program that does not match the source.
func newBuildCmd() *cobra.Command {
	var output string
	var emitGo string
	var allowCgo bool

	cmd := &cobra.Command{
		Use:   "build <entry>",
		Short: "Compile a TypeScript or JavaScript entry to a single native binary",
		Long: "Build type-checks the entry module, lowers it to Go, and compiles that\n" +
			"Go to a native binary. With no -o the binary takes the entry's base name.\n" +
			"With --emit-go it writes the generated Go source instead of a binary, which\n" +
			"is how the benchmark suite records the code each workload compiles to.",
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("emit-go") {
				source, err := build.EmitGo(args[0], versionStamp())
				if err != nil {
					return err
				}
				if emitGo == "" || emitGo == "-" {
					_, err := fmt.Fprint(cmd.OutOrStdout(), source)
					return err
				}
				return os.WriteFile(emitGo, []byte(source), 0o644)
			}
			if err := build.Build(build.Options{Entry: args[0], Output: output, AllowCgo: allowCgo}); err != nil {
				return err
			}
			return nil
		},
	}
	cmd.Flags().StringVarP(&output, "output", "o", "", "path of the native binary to write (default: entry base name)")
	cmd.Flags().StringVar(&emitGo, "emit-go", "", "write the generated Go source to this path (\"-\" for stdout) instead of building a binary")
	cmd.Flags().BoolVar(&allowCgo, "allow-cgo", false, "acknowledge that a go: import needs cgo, forfeiting the zero-cgo cross-compile, and build it anyway")
	return cmd
}

// versionStamp is the short build identifier written into an --emit-go header, the
// bento version and commit stamped into this binary at release time. A golden
// generated by a dev build reads "dev (commit none)", which still records that the
// code came from an unreleased build rather than leaving its origin unstated.
func versionStamp() string {
	return fmt.Sprintf("%s (commit %s)", Version, Commit)
}
